### ISSUE TITLE
Export Error in ChatGPT and ChatGPT-3.5-Turbo Menu

### ISSUE THREAD

**Issue by InstaZDLL** [obiscr/ChatGPTGold#6]
I have an error when **I want to export** the conversation, I have this error and It appear in **ChatGPT** and **ChatGPT-3.5-Turbo**.
IDE I'm using : **PyCharm 2023.1.1 (Professional Edition) / Build #PY-231.8770.66, built on April 27, 2023**

### The error in question: both export options don't work
```java
java.lang.NoClassDefFoundError: org/apache/tools/ant/util/DateUtils
  at com.obiscr.chatgpt.util.f.a(f.java:51)
  at com.obiscr.chatgpt.util.f.a(f.java:37)
  at com.obiscr.chatgpt.a.u.run(u.java:366)
  at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
  at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
  at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
  at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
  at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
  at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
  at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
  at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
  at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
  at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.util.DateUtils PluginClassLoader(plugin=PluginDescriptor(name=ChatGPTGold, id=ChatGPTGold, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2023.1\plugins\ChatGPTGold, version=2023.5.1-223.231, package=null, isBundled=false), packagePrefix=null, instanceId=75, state=active)
  at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
  ... 23 more

```

![Screenshot 2023-05-15 113146](https://github.com/obiscr/ChatGPTGold/assets/72951793/ed967eda-6184-4ab5-b2a9-627ea171c3c5)
![2023-05-15 11_30_40-FlaskWebS – README md](https://github.com/obiscr/ChatGPTGold/assets/72951793/edceff0f-38fb-4645-9a45-d8dd0bc21c54)
![Screenshot 2023-05-15 114811](https://github.com/obiscr/ChatGPTGold/assets/72951793/01bb5f84-6841-4c65-b912-a090aaed9ae6)

**Comment by obiscr** [comment]
Thank you for your report. I will handle it.

**Comment by obiscr** [comment]
It's a bug, and will be fixed in the next version.

**Comment by InstaZDLL** [comment]
Perfect, I no longer have any problems when I export 👍
